export const dummyData = [
  {
    id: 'EVT001',
    name: 'Tech Conference 2024',
    email: 'organizer1@example.com',
    phone: '+1 (345) 555-0101',
    startDate: '2025-05-15',
    endDate: '2025-05-16',
    startTime: '09:00',
    endTime: '17:00',
    description: 'Annual technology conference featuring the latest innovations...',
    amount: 2500,
    status: 'completed',
    submittedDate: '2025-05-17',
    organizer: 'John Doe',
    venue: 'Tech Convention Center',
    expectedAttendees: 500,
    requirements: 'High-speed internet, AV equipment, catering services'
  },
  {
    id: 'EVT002',
    name: 'Music Festival',
    email: 'festival@example.com',
    phone: '+1 (345) 555-0102',
    startDate: '2025-05-20',
    endDate: '2025-05-22',
    startTime: '10:00',
    endTime: '23:00',
    description: 'Summer music festival with international artists and local bands...',
    amount: 3500,
    status: 'pending',
    submittedDate: '2025-05-25',
    organizer: 'Sarah Wilson',
    venue: 'Central Park Arena',
    expectedAttendees: 2000,
    requirements: 'Sound system, lighting, security, food vendors'
  },
  {
    id: 'EVT003',
    name: 'Business Workshop',
    email: 'workshop@example.com',
    phone: '+1 (345) 555-0103',
    startDate: '2025-05-05',
    endDate: '2025-05-05',
    startTime: '13:00',
    endTime: '17:00',
    description: 'Leadership and management skills development workshop...',
    amount: 1200,
    status: 'cancelled',
    submittedDate: '2025-05-20',
    organizer: 'Michael Brown',
    venue: 'Business Center',
    expectedAttendees: 100,
    requirements: 'Projector, whiteboards, workshop materials'
  },
  {
    id: 'EVT004',
    name: 'Art Exhibition',
    email: 'art@example.com',
    phone: '+1 (345) 555-0104',
    startDate: '2025-05-10',
    endDate: '2025-05-15',
    startTime: '10:00',
    endTime: '18:00',
    description: 'Modern art showcase featuring local and international artists...',
    amount: 1800,
    status: 'pending',
    submittedDate: '2025-05-18',
    organizer: 'Emma Davis',
    venue: 'City Art Gallery',
    expectedAttendees: 300,
    requirements: 'Display panels, lighting, security system'
  },
  {
    id: 'EVT005',
    name: 'Sports Tournament',
    email: 'sports@example.com',
    phone: '+1 (345) 555-0105',
    startDate: '2025-05-01',
    endDate: '2025-05-03',
    startTime: '08:00',
    endTime: '20:00',
    description: 'Regional sports competition with multiple disciplines...',
    amount: 4200,
    status: 'completed',
    submittedDate: '2025-05-15',
    organizer: 'Tom Johnson',
    venue: 'Sports Complex',
    expectedAttendees: 1000,
    requirements: 'Sports equipment, medical staff, refreshments'
  },
  {
    id: 'EVT006',
    name: 'Food Festival',
    email: 'food@example.com',
    phone: '+1 (345) 555-0106',
    startDate: '2025-05-15',
    endDate: '2025-05-17',
    startTime: '11:00',
    endTime: '22:00',
    description: 'International cuisine festival with top chefs and workshops...',
    amount: 2800,
    status: 'cancelled',
    submittedDate: '2025-05-10',
    organizer: 'Lisa Chen',
    venue: 'Food Court Plaza',
    expectedAttendees: 800,
    requirements: 'Cooking stations, refrigeration, dining area'
  },
  {
    id: 'EVT007',
    name: 'Science Fair',
    email: 'science@example.com',
    phone: '+1 (345) 555-0107',
    startDate: '2025-05-20',
    endDate: '2025-05-22',
    startTime: '09:00',
    endTime: '16:00',
    description: 'Student science exhibition with innovative projects...',
    amount: 1500,
    status: 'pending',
    submittedDate: '2025-05-05',
    organizer: 'David Miller',
    venue: 'Science Center',
    expectedAttendees: 400,
    requirements: 'Display tables, power outlets, safety equipment'
  },
  {
    id: 'EVT008',
    name: 'Wedding Expo',
    email: 'wedding@example.com',
    phone: '+1 (345) 555-0108',
    startDate: '2025-05-14',
    endDate: '2025-05-15',
    startTime: '10:00',
    endTime: '19:00',
    description: 'Wedding planning exhibition with vendors and fashion shows and more Wedding planning exhibition with vendors and fashion shows and more Wedding planning exhibition with vendors and fashion shows and more Wedding planning exhibition with vendors and fashion shows and more',
    amount: 3200,
    status: 'completed',
    submittedDate: '2025-05-01',
    organizer: 'Rachel White',
    venue: 'Grand Hotel',
    expectedAttendees: 600,
    requirements: 'Stage, dressing rooms, vendor booths'
  },
  {
    id: 'EVT009',
    name: 'Career Fair',
    email: 'career@example.com',
    phone: '+1 (345) 555-0109',
    startDate: '2025-03-01',
    endDate: '2025-03-02',
    startTime: '09:00',
    endTime: '17:00',
    description: 'Job and career exhibition',
    amount: 2100,
    status: 'pending',
    submittedDate: '2025-05-07',
    organizer: 'Mark Thompson',
    venue: 'Convention Hall',
    expectedAttendees: 1500,
    requirements: 'Interview booths, presentation area'
  },
  {
    id: 'EVT010',
    name: 'Gaming Convention',
    email: 'gaming@example.com',
    startDate: '2025-04-05',
    endDate: '2025-04-07',
    startTime: '10:00',
    endTime: '20:00',
    description: 'Gaming and esports event',
    amount: 5000,
    status: 'pending',
    submittedDate: '2025-05-06',
    organizer: 'Alex Rodriguez',
    venue: 'Gaming Arena',
    expectedAttendees: 2500,
    requirements: 'Gaming setups, tournament area, streaming equipment'
  }
] 